### ISSUE TITLE
app should handle pcap post warnings

### ISSUE THREAD

**Issue by mccanne** [brimsec/brim#1028]
Zqd has a new API message with type field "PcapPostWarning" that has the same form and use as LogPostWarning.  The app should be ready to receive this on PcapPostRequest.

The warning shouldn't be modal and interrupt the user but there should be a visual cue in the UI.

This was added to delay with funkiness we're finding in various pcaps and the warnings could be useful in diagnosing problems from users who can't share their pcaps with us.

**Comment by philrz** [comment]
I got a feel for how this looks while verifying the fix in https://github.com/brimsec/zq/issues/1117. The app currently shows no error message, but it's visible if you sniff in Wireshark during the import of a file such as the attached [bad.pcapng.zip](https://github.com/brimsec/brim/files/5139546/bad.pcapng.zip) (uncompress before importing). An example request:

```
POST /space/sp_1ghs0BczuKhYsDXVbEwFXlnLMwg/pcap HTTP/1.1
Host: localhost:9867
Connection: keep-alive
Content-Length: 41
sec-ch-ua: 
Origin: file://
Sec-Fetch-Dest: empty
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Brim/0.15.1 Chrome/78.0.3904.130 Electron/7.3.2 Safari/537.36
Content-Type: text/plain;charset=UTF-8
Accept: */*
Sec-Fetch-Site: cross-site
Sec-Fetch-Mode: cors
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US

{"path":"/Users/phil/Desktop/bad.pcapng"}
```

The response, which shows the warning that's not yet surfaced into the app:

```
Content-Type: application/ndjson
X-Request-Id: 16
Date: Fri, 28 Aug 2020 01:25:32 GMT
Transfer-Encoding: chunked

23
{"type":"TaskStart","task_id":2}



4c
{"type":"PcapPostWarning","warning":"pcap-ng has extra bytes at eof: 20"}



10f
{"type":"PcapPostStatus","start_time":{"sec":1598577932,"ns":887796000},"update_time":{"sec":1598577933,"ns":886545000},"pcap_total_size":12401,"pcap_read_size":12401,"snapshot_count":1,"span":{"ts":{"sec":1583768523,"ns":826851000},"dur":{"sec":6349,"ns":865915001}}}



1f
{"type":"TaskEnd","task_id":2}

0
```

**Comment by philrz** [comment]
While walking through some old issues I spotted #537, which is a good reminder that a test here would prove helpful, too.

**Comment by philrz** [comment]
Verified in Brim commit `36406be` when using GA Brim Zeek tagged `v3.2.0-dev-brim10`.

Alas, things change too fast! In the time we were working on this issue, we updated our Zeek artifacts to be based on Zeek `v3.2.1`, whereas when the issue was first opened we were using ones based on a `v3.2.0-dev` commit. Whereas in the past Zeek would quietly ingest the "bad.pcapng" linked above and a warning would come from our backend's pcap handler, now even "stock" Zeek `v3.2.1` actually _fails_ to ingest it:

```
$ /usr/local/zeek-3.2.1/bin/zeek -C -r ~/Desktop/bad.pcapng local
WARNING: No Site::local_nets have been defined.  It's usually a good idea to define your local networks.
1583774873.692766 fatal error: failed to read a packet from /Users/phil/Desktop/bad.pcapng: truncated pcapng dump file; tried to read 8 bytes, only got 1

$ echo $?
1
```

Therefore when running with Brim commit `36406be` out-of-the-box and this particular test data, the failure from the newer Zeek dominates and the warning is never seen.

So to test, I manually replaced `zdeps/zeek/` in my local Brim checkout with the contents of the `v3.2.0-dev-brim10` artifact, since Zeek was tolerant back then. Now, per the attached video, when I drag in the "bad.pcapng", I do see the warning icon and can click it and see the details.

[Verify.zip](https://github.com/brimsec/brim/files/5357916/Verify.zip)

Therefore, if we _do_ get to a spot where there's genuine warnings again, they should make it through to the app and the user.

Thanks @jameskerr!
