### ISSUE TITLE
how to extract the packet from the conn of zeek 

### ISSUE THREAD

**Issue by xx-zhang** [brimsec/brim#1170]
> **i want to extract the tcp payload or packet from the tcp conn of zeek. how can i make it dump to local file or hex to tcp_payload param into the brim log.**

Here is a squid pcap that we can't get the tcp payload from brim but only conn info. of course we can view the packet in `moloch` i also want to see the log showing like that. 
![image](https://user-images.githubusercontent.com/47806549/97380998-23229f80-1903-11eb-8a7a-63b9a016a82c.png)

[dump_squid_01.zip](https://github.com/brimsec/brim/files/5449047/dump_squid_01.zip)

**Comment by philrz** [comment]
Thanks for your interest in Brim, @xx-zhang!

As you've observed, Brim doesn't currently present extracted TCP payloads automatically. Assuming you started by importing the pcap to Brim, the quickest way to get at them with Brim currently would be to click the "Packets" button or right-click on an event (such as the `conn` event as you noted) and select "Download PCAPS", which will extract just that flow and open it in Wireshark. Then in Wireshark you can right-click and select "Follow TCP Stream" and it will show you the payload

![image](https://user-images.githubusercontent.com/5934157/97460928-73493400-18fa-11eb-9053-ad7ae22636eb.png)

Since this is a common operation in Brim, I'm guessing you may have already known that, so maybe what you're asking is if there could be a way to have these payload extractions always performed so they could be shown immediately within Brim as soon as they're available? This isn't possible today, but it's a request that's come up before. There's an open issue #1104 where we describe some of the ways to partially achieve this today (via [Zeek Customization](https://github.com/brimsec/brim/wiki/Zeek-Customization)), as well as some of the complexity we see related to adding this as a general feature. Please read through that issue and let me know if you have any questions or if I've misunderstood what you're trying to achieve. Once I've heard from you, my inclination is to close _this_ issue as a duplicate of #1104 and we'll have your inquiry as record of another user that would benefit from the feature.

Will wait to hear from you.

**Comment by xx-zhang** [comment]
@philrz Thank you very much, you have helped me a lot. Hope `brim` better and better by heart. best with to you .
