### ISSUE TITLE
Missing space list and open space details on Windows at startup

### ISSUE THREAD

**Issue by alfred-landrum** [brimsec/brim#1281]
I saw this issue with the Brim v0.21.0 release candidate on Windows: Occasionally when I opened Brim, I would see that 'spaces' left side menu was empty, and expanding/collapsing it didn't make a difference, and the details under the space name were "nan undefined 0ms".

I wondered if this was some type of zqd issue, so I made sure that I could use zapi to get the expected space details. I also reproduced this when I already had zqd running when Brim started.

<img width="412" alt="image" src="https://user-images.githubusercontent.com/704945/102161591-75306d80-3e3c-11eb-98ce-88fa5be8ef54.png">

**Comment by jameskerr** [comment]
@alfred-landrum was there a series of steps to reproduce this. Or at least have a good chance of reproducing this?

**Comment by alfred-landrum** [comment]
@jameskerr : I saw it by selecting a space (ensuring the default search view was visible), then repeatedly closing the app, waiting a second & re-opening it, and it would eventually manifest.

**Comment by philrz** [comment]
One thought: The way the update logic works today, despite the RC being versioned as v0.21.0, the app would be trying to check for a newer version and auto-update itself in the background. At one point on my Mac I'd though I'd repro'ed this issue but I'd forgotten that I'd already seen & acknowledged the "Later" button to restart at the auto-updated v0.20.0. It seems like downgrading to v0.20.0 _definitely_ makes the Spaces disappear, as I've witnessed this on my Mac. Maybe you were not being downgraded and witnessed a different issue (I didn't witness any "nan undefined 0ms", just empty Spaces), but just wanted to put it out there.

**Comment by philrz** [comment]
I've attached a video of a repro that's quite consistent on Windows using yesterday's Brim `v0.21.0` release candidate that was based on commit `6bb51cb`. The attached [hello.zip](https://github.com/brimsec/brim/files/5699523/hello.zip) is imported (must be unzipped first), once the "Import complete" pop-up is acknowledged, select File->Exit from the drop-down menu and immediately relaunch Brim. The Spaces menu is empty and you can see the "NAN UNDEFINED" as shown in the original repro screenshot.

[Repro.zip](https://github.com/brimsec/brim/files/5699522/Repro.zip)

I did also successfully repro earlier on macOS using the same steps.

**Comment by philrz** [comment]
@jameskerr: I just tried to verify this on Windows using a new draft release artifact based on Brim commit `e0c7d24` that includes this fix. Per the attached video, now when I close the app and reopen it repeatedly, the Spaces list is always populated. So, that's major progress. However, you can see the "NAN UNDEFINED" still appears in the main window below the Space name. I know this is cosmetics rather than serious breakage, but since the fix is still fresh in your mind and the release hasn't gone out yet, want to give it another look? The previous comment includes a link to the test pcap I used to repro.

[Partial-Verify.zip](https://github.com/brimsec/brim/files/5699574/Partial-Verify.zip)

**Comment by philrz** [comment]
I've now also verified the additional fix in #1288 using a scratch Brim release artifact based on commit `e0c7d24`. Per the attached video, now after selecting File->Exit and relaunching the app, accurate Space details are once again shown instead of the "NAN UNDEFINED" that was present due to the bug.

[Verify.zip](https://github.com/brimsec/brim/files/5704835/Verify.zip)

Thanks @jameskerr!
