### ISSUE TITLE
 Non-standard ports cannot be recognized as http

### ISSUE THREAD

**Issue by nmweizi** [brimsec/brim#1407]
- Non-standard ports cannot be recognized as http

![image](https://user-images.githubusercontent.com/1232444/106616045-0eac0e00-65a8-11eb-8237-c0f779ccbfb5.png)

**Comment by philrz** [comment]
@nmweizi: Thanks for reporting. What you describe would be an issue with [Zeek](https://zeek.org/), which is another open source project that's embedded with the Brim app. We have a fair amount of knowledge about Zeek and contribute to that project, but ultimately this type of issue is something we'd want to take up with them.

As a general statement, we've observed that Zeek typically _does_ identify HTTP traffic on non-standard ports. To show you an example with a publicly available pcap so you can try for yourself, you can download/uncompress the one at https://archive.wrccdc.org/pcaps/2018/wrccdc.2018-03-23.010232000000000.pcap.gz and import that into Brim. Here you can see the many HTTP events identified on non-standard ports:

![image](https://user-images.githubusercontent.com/5934157/106627072-42961d80-652d-11eb-9274-8730573349ad.png)

If you right-click on a row like the one for `8093` and select "Pivot to logs", that'll bring ip the event:

![image](https://user-images.githubusercontent.com/5934157/106627175-60fc1900-652d-11eb-8e4c-9ba29790bf79.png)

You can then click the Packets button and see the extracted flow in Wireshark.

![image](https://user-images.githubusercontent.com/5934157/106627289-8426c880-652d-11eb-839d-1466144c92b3.png)

The reason why it didn't work for you is likely something unique about your traffic. My best guess is that there's something about the traffic that made it "not quite HTTP enough" for their protocol parser to reliably identify it as such. I see in your screenshot that there's a `weird` event also logged for this flow, so if you click on that, it may show some evidence.

If you'd like to get to the bottom of it, the only way I see forward is to come up with traffic that reproduces the problem. Since you blanked out parts of your screenshot, I'm guessing that your pcap is sensitive and you may not be able to share it as-is. However, if you're able to do a controlled reproduction with non-sensitive traffic, isolate just the one flow that triggers the problem and find it's ok to share, or are able to anonymize the pcap in a way that still reproduces the symptom, that would be something we could take up with the Zeek development team. If this is something you think you could discuss directly with me 1-on-1 but not out in the open on GitHub Issues, feel free to [join our public Slack](https://www.brimsecurity.com/join-slack/) and message me directly there as `@phil`.

I'll hold this issue open in hopes we hear from you. Thanks for your interest in Brim!

**Comment by nmweizi** [comment]
thank you very much
Let me try
