### ISSUE TITLE
Log Detail pane crashes when expected fields are missing

### ISSUE THREAD

**Issue by jameskerr** [brimsec/brim#1475]
If a record in the viewer is clicked on that has a `uid` and a `community_id`, but missing `ts` or `duration`, the app will crash if the detail pane is opened.

I was able to reproduce this bug by running this query, then opening the detail pane:

```
_path=conn | cut _path, uid, community_id, ts
```
<img width="841" alt="image" src="https://user-images.githubusercontent.com/3460638/108405860-7aac8a00-71d6-11eb-8d78-d85a267d0250.png">

Then if I click on the first result and open the detail pane: 

<img width="841" alt="image" src="https://user-images.githubusercontent.com/3460638/108405932-9021b400-71d6-11eb-8852-ebc51a4bc996.png">

**Comment by philrz** [comment]
I did a bit more digging into this, as the inquiry started on a [Brim public Slack thread](https://brimsec.slack.com/archives/C010DR0HHMF/p1613669562048600) and the user didn't speak of having to do any special `cut` in order to trigger the problem. I get even more nervous if out-of-the-box data can trigger an issue, so I wanted to make sure we fully understand what's going on here.

The user explained the logs in question are "Corelight-specific" Suricata. Having looked at the error message, @jameskerr explained:

> I think this bug is in the uid correlation view in the detail pane of the app.  It expects a record with both a “uid” and a “community_id” to be a traditional zeek conn record. Traditional conn records have a “duration” field. That duration value is used to set the time frame of the correlation view. However, it looks like the data you’re viewing has “uid” and “community_id” fields, but no “duration”.

I happen to have an eval Software Sensor v1.3.3, so I went ahead and ran some test traffic to generate this Suricata log [suricata_corelight-softsensor.log.gz](https://github.com/brimsec/brim/files/6006317/suricata_corelight-softsensor.log.gz):

```
#separator \x09
#set_separator	,
#empty_field	(empty)
#unset_field	-
#path	suricata_corelight
#open	2021-02-18-13-01-30
#fields	_path	_system_name	_write_ts	_node	ts	uid	id.orig_h	id.orig_p	id.resp_h	id.resp_p	suri_id	service	flow_id	tx_id	pcap_cnt	alert.action	alert.gid	alert.signature_id	alert.rev	alert.signature	alert.category	alert.severity	alert.metadata	community_id	metadata	retries
#types	string	string	time	string	time	string	addr	port	addr	port	string	string	count	count	count	string	count	count	count	string	string	count	vector[string]	string	vector[string]	count
suricata_corelight	phil-VirtualBox	1613682090.154494	worker-01	1613682090.153543	COX0ZK1Tj5bJstDXGh	10.0.2.15	60134	104.21.25.86	80	S703NryV4OE6	http	1274071273249241	0	0	allowed	1	2013028	5	ET POLICY curl User-Agent Outbound	Attempted Information Leak	2	updated_at:2020_04_22,created_at:2011_06_14	-	-	-
#close	2021-02-18-13-02-02
```

Despite the fact this meets @jameskerr's criteria that it "has `uid` and `community_id` fields, but no `duration`" it did not trigger the problem in my GA Brim tagged `v0.24.0`. As you can see, it simply says "Duration: Not available".

![image](https://user-images.githubusercontent.com/5934157/108430594-709a8380-71f6-11eb-9c71-6fd7e1e9affc.png)

@jameskerr then checked my test data against the code and saw that the reason I was evading the bug is because my `community_id` is `null`. I checked with the originator of the issue (who happens to work for Corelight) who confirmed that his particular Suricata log came off a Corelight Sensor _Appliance_, which apparently _does_ populate `community_id` of Suricata alerts, whereas that's not currently supported on the Software Sensor.

Therefore, if I manually populate `community_id` with a value to make it look like the ones that come from the appliance, such as in this [suricata_corelight-softsensor-modified.log.gz](https://github.com/brimsec/brim/files/6006338/suricata_corelight-softsensor-modified.log.gz):

```
#separator \x09
#set_separator	,
#empty_field	(empty)
#unset_field	-
#path	suricata_corelight
#open	2021-02-18-13-01-30
#fields	_path	_system_name	_write_ts	_node	ts	uid	id.orig_h	id.orig_p	id.resp_h	id.resp_p	suri_id	service	flow_id	tx_id	pcap_cnt	alert.action	alert.gid	alert.signature_id	alert.rev	alert.signature	alert.category	alert.severity	alert.metadata	community_id	metadata	retries
#types	string	string	time	string	time	string	addr	port	addr	port	string	string	count	count	count	string	count	count	count	string	string	count	vector[string]	string	vector[string]	count
suricata_corelight	phil-VirtualBox	1613682090.154494	worker-01	1613682090.153543	COX0ZK1Tj5bJstDXGh	10.0.2.15	60134	104.21.25.86	80	S703NryV4OE6	http	1274071273249241	0	0	allowed	1	2013028	5	ET POLICY curl User-Agent Outbound	Attempted Information Leak	2	updated_at:2020_04_22,created_at:2011_06_14	1:n4XOpMl5fGAvVRApUbCEUQH2X98=	-	-
#close	2021-02-18-13-02-02
```

...now I've got a solid repro! I just drag that in, open the Log Detail Panel, and:

![image](https://user-images.githubusercontent.com/5934157/108430995-1cdc6a00-71f7-11eb-80dd-f3c90872db14.png)

**Comment by philrz** [comment]
Verified in Brim commit 1004414.

Repeating the repro steps described in the lowermost comment above, now when we open the Log Detail pane and click an event, there's no longer a crash.

https://user-images.githubusercontent.com/5934157/110013869-fdedd580-7cd6-11eb-8739-f2f8665b5577.mov

Thanks @jameskerr!
