### ISSUE TITLE
New window for Log Details pane

### ISSUE THREAD

**Issue by philrz** [brimsec/brim#557]
Per @siskojr:

---

Proposal: Decouple the main Log (events) pane from the Log Details pane. The Log Details pane would become a new window.

When a user double-clicks an event for the first time, a new window with the Log Details will appear.

When a user clicks an event in the main Log pane, we update the Log Details window.

When a user moves to a new event in the main Log pane with arrow keys, we also update the Log Details window.

The user might end up using various simultaneous Log Details windows. On double-click, provide the option to open a new Log Details window (tied to current Logs window) or re-use the current active one. This is:

1. Mode with a single Log Details window open. All changes in the Logs window update the same Log Details Window.
2. Dual Log Details Window (A use case with two active Log Details windows using two monitors is the most likely one. In this case user has to decide to what Side to “project” the log.)
3. N- Log Details windows. This case may be less common but users will associate windows of logs (would contain multiple tabs) to the same window of Log Details.

Mode 1,2 are required. Mode 3 is desired.

**Comment by mason-fish** [comment]
**UPDATE**

After discussing, we have come to a consensus for this feature with the following details:

* The current 1:1 relationship between tab's search and detail-pane will remain, such that each detail-pane will dynamically reflect any selected/single-clicked logs from it's corresponding search page. Note, the word "pane" here is chosen because the log detail view is attached to the search results view.

* Within the detail-pane, there will be an icon (something like [↗]) to facilitate the new feature of opening that specific log detail in a detached window. This detached detail-window will present all of the same content as the detail-pane had (and may even annotate additional metadata), but it will no longer be associated with any tab's search results. Meaning it will *not* dynamically change if a different log is clicked on in any tab's search results. The detail-window may be thought of as "static" in this regard, as opposed to the "dynamic" changing which the detail-pane.

* The detail-window can also be directly opened up by double clicking a log within a tab's search results.

* Within the detail-window:
  * Search-related operations, such as filtering on one of the log detail's values, will create a new tab (in the last focused window, or a new one if none exist) with the new filtered search that was chosen.
  * Operations which would result in viewing a different log detail, such as clicking an http log that is among the uid correlation set, will display that selected log detail in the *same* detail-window, and will provide and maintain it's own log navigation/browsing history (using the existing [←] and [→] ui that the detail-pane has).

**Comment by philrz** [comment]
Verified in Brim commit `1fae48f`.

Per the attached video, now there's the ↗ control in the Log Detail panel that can be clicked to pop out its contents into an independent window. Also, double-clicking on an event in the main events panel immediately pops out that event into an independent window. Finally, right-click operations within a popped out window that invoke a new query (such as "New search with this value") start in a new tab.

[Verify.zip](https://github.com/brimsec/brim/files/4533560/Verify.zip)

Thanks @mason-fish!
