### ISSUE TITLE
UX: progress bar to show processing logs

### ISSUE THREAD

**Issue by siskojr** [brimsec/brim#567]
Update the message for the progress bar to reflect that we are ingesting zeek logs. 

Reusing same progress bar as for packets but changing the message to "Processing Logs"

![processing_logs.jpg](https://images.zenhubusercontent.com/5e8b7dd61f02b3461f7761d3/7a02e193-28e0-4137-9534-d3ad9572b0b1)

**Comment by alfred-landrum** [comment]
@siskojr : I'm keeping this open so you can review: the changes have been merged, so we are showing an active progress bar during log ingest. The text displayed during ingest has changed since you filed this, so for pcaps or logs, there's no "Processing <type>" message anymore. 

FYI that there's no support right now for issuing queries against data from ingested logs while the ingest is in process. If/when we want that, we'll need to allocate time for it.

**Comment by siskojr** [comment]
Thanks. Pulled the latest version of Brim and verified all. Makes sense.  
Log ingest is very fast so waiting to issue queries 
I see that we have removed the limit of size, fantastic.
J
