### ISSUE TITLE
feature to enter pre-master secret to decrypt TLS traffic

### ISSUE THREAD

**Issue by 0xmilkmix** [brimsec/brim#608]
When performing malware analysis in a sandbox it is possible to retrieve the pre-master secret and decrypt the TLS traffic in Wireshark using it. See https://isc.sans.edu/forums/diary/German+malspam+pushes+ZLoader+malware/25996/ for example.

**Describe the solution you'd like**
Global menu or contextual menu to allow loading a pre-master secret file and process TLS traffic.

**Comment by philrz** [comment]
@0xmilkmix: Thanks for your interest in Brim & submitting this request. My colleague Javier (@siskojr) has some questions on your expected use for this he'd like to ask you. Could you join the public Slack system we have set up for Brim support? I imagine it'd be easiest for the two of you to chat on there and then we can summarize the next steps here.

The link to send yourself an invite to the public Slack:

https://join.slack.com/t/brimsec/shared_invite/zt-cy34xoxg-hZiTKUT~1KdGjlaBIuUUdg

**Comment by siskojr** [comment]
Hi @0xmilkmix,


Thanks for your interest in Brim. 
 
Encrypted traffic is of special relevance for us and  we will be adding some improvements, like support for JA3/JA3S/HASSH and other fingerprinting methods for SSL that work on encrypted form.
 
 
Some of the considerations that we keep in mind to prioritize our efforts  are:
* We  try not to reproduce Wireshark functionality.
* "SSL is becoming the new TCP" and technologies like Zero Trust are replacing IPSEC-VPNs with SSL/TLS transport.
* With Perfect Forward Secrecy (PFS) the master secret is not enough to derive the session key.  The session key would be needed, from the client, server or trusted MITM. Firefox and Chrome allow logging of it, hard to manage, though doable in cases like the sandbox example that you mention.
* Adoption of Forward secrecy is increasing. Ref: https://www.ssllabs.com/ssl-pulse/
* NIST recommendations to support TLS1.3 by January 2024 for government servers. https://csrc.nist.gov/publications/detail/sp/800-52/rev-2/final
 
 
One of the questions I had was about the SSL traffic volume.  In the example about ZLoader the pcaps are small, 59KB, doable in Wireshark. 
In general, are you working with big pcap files that contain only a percentage of SSL/TLS traffic that you want to analyze?  If this is your case, we may have a solution for you:
 
1. Filter the traffic you are interested in with a ZQL query (example, _path=ssl and 51.83.216.232)(the IP in the client hello of ZLoader example)
2. Export all that relevant traffic, in bulk, from Brim to Wireshark. 
3. Use the  built-in functionality in Wireshark to decrypt the traffic.
 
If these steps work for you, then we will have a solution because we are working in a feature to be able to export multiple flows (connections) to Wireshark.
 
Let me know if this makes sense for you.
 
Best regards.
 
J

**Comment by 0xmilkmix** [comment]
Hello,

Thanks for the clarifications. It wasn't clear for me to which extend you would like to match Wireshark features for security analysts. I indeed didn't thought about PFS, thanks for pointing that out!

In our case for sandbox it's rather small pcap so indeed, Wireshark would be ok.

Looking forward to see the fingerprinting based features.

Thank you and best regards

**Comment by siskojr** [comment]
Thanks to you.
Cheers
J
