### ISSUE TITLE
Capture length exceeds original packet length: 84 > 68

### ISSUE THREAD

**Issue by harold-yh** [brimsec/brim#615]
When I open a pcap file,I got this tips:
Capture length exceeds original packet length: 84 > 68

wireshark can open the pcap file.
![image](https://user-images.githubusercontent.com/28439656/79290971-fe834f00-7eff-11ea-8e7f-2a092d04dc53.png)

[000.pcap.zip](https://github.com/brimsec/brim/files/4479145/000.pcap.zip)

MAC OS
Release Version:0.7.0

**Comment by philrz** [comment]
@harold-yh: Thanks for submitting the issue and including the pcap. We've seen symptoms like this before, so I expect we'll be able to figure it out. Out of curiosity, do you know what kind of device/tool created the capture, and any particular config/flags that were in use during creation?

**Comment by mccanne** [comment]
Fixed here https://github.com/brimsec/zq/pull/584

**Comment by philrz** [comment]
Verified in `pcap` commit `c2fd2f8`.

To revisit the original repro, as of `pcap` commit `03d248a`:

```
# pcap index -r 000.pcap -x 000.idx
capture length exceeds original packet length: 84 > 68
```

Now in `pcap` commit `c2fd2f8`:

```
# pcap index -r 000.pcap -x 000.idx
# ls -l 000.idx 
-rw-r--r--  1 phil  staff  364924 Apr 15 14:16 000.idx
```

@harold-yh: This is now fixed in the `zq` code base, which the Brim app ultimately uses for processing pcaps. Therefore you'll see the benefit of the fix in the next Brim release we tag. Lately we've been creating Brim releases on average once per week. Since you're on MacOS, as long as you're running Brim `v0.6.0` or newer, your app should "auto-update" to the new release once it's available (you'll be prompted in-app). Another way to keep up with releases and community activity is to join our [public Slack](https://join.slack.com/t/brimsec/shared_invite/zt-cy34xoxg-hZiTKUT~1KdGjlaBIuUUdg) system. Thanks for helping to improve Brim!

**Comment by philrz** [comment]
@harold-yh: Heads-up that the new Brim release [v0.8.0](https://github.com/brimsec/brim/releases/tag/v0.8.0) that just went up has a fix for this issue. Let us know if any other troubles come up. Thanks for using Brim!
