### ISSUE TITLE
Improve rendering of Chart/Logs during ingest 

### ISSUE THREAD

**Issue by siskojr** [brimsec/brim#616]
**Request** 

While ingest:
1.  if user has not typed any query, auto-update the chart and log pane when new data of ingest process arrives.
2. If user has typed a query, provide a tooltip message indicating that new data has arrived and query needs to be re-run.  
  - The tooltip message will signal the user who prefers keyboard to type return key. 
- A refresh button would simplify the user action when  mouse clicks are preferred. 

The progress bar will continue to indicate information about the processing of the file and auto-update will help the user by refreshing the chart and logs in a dynamic way till the processing of file ends. 

**Description of current  behavior and possible issues:**

When opening a pcap file, the progress bar provides a good indication of the processing of the pcap file.
However, the Chart that is plot while reading packets and the initial list of logs that we render, do not change during ingest unless there is some user intervention. 
The user does not have feedback that more data/logs are available and gets the impression that data is missing, The user would have to type return key to update the screen or select the  Whole Space repeatedly, but there is no clear indication when new data is available, other than guessing from the progress bar movement.

The following screen shows the case where a single log is shown. Since there is no change, the user gets confused.

![image.png](https://images.zenhubusercontent.com/5e8b7dd61f02b3461f7761d3/ced1864f-1c15-400c-bfbf-b3bc2d6dd20b)

The following screen shows a case where some logs are rendered, but the Chart shows no data. 

![image.png](https://images.zenhubusercontent.com/5e8b7dd61f02b3461f7761d3/13a1cc5f-2561-4daa-bd4c-e02b632ab9b1)

**Comment by philrz** [comment]
Verified in Brim commit `33f28aa` talking to `zqd` commit `a09d0d6`.

In the first video I'm a user of the "lean back" variety. I've started import of my pcap and I'm not trying to run queries or otherwise interact with the Brim app. Without any action on my part, the app keeps refreshing me to show the most recent events and the histogram gets filled in with more bars. This repeats until the pcap is fully imported.

[Verify-Lean-Back.mp4.zip](https://github.com/brimsec/brim/files/4566598/Verify-Lean-Back.mp4.zip)

In the second video I'm a more interactive user. I've started to run a query while ingest is still happening. To be minimally disruptive to my work, the "More data is now available" notice pops up from below, and I'm able to incorporate that data into my query by clicking the "Refresh" button or hitting Enter on my current query (or a new one).

[Verify-Interact.mp4.zip](https://github.com/brimsec/brim/files/4566604/Verify-Interact.mp4.zip)

Thanks @jameskerr!
