### ISSUE TITLE
change release artifact names

### ISSUE THREAD

**Issue by alfred-landrum** [brimsec/brim#619]
We make our releases available at https://www.brimsecurity.com/download with links that guide user to the correct link for their platform. For anyone that comes to our releases page, though, it may take a minute to figure out what they should grab. So for the next release, we'll rename the artifacts:
```
Brim-Windows-Installer.exe
Brim-MacOS.dmg
brim-darwin-update-artifact.zip
```

**Comment by nwt** [comment]
Brim-macOS.dmg since Apple styles it macOS?

**Comment by philrz** [comment]
Closing this one as a "Won't Fix". We're going to be adding more to the artifacts list when we start doing Linux releases, so this list is going to get longer and no single naming scheme in the Artifacts list is likely to make it 100% clear. Our thinking is that I'll start putting a pointer to the Downloads page as the top item in the bullets on the Releases tab, since that gives us a web page where we can more clearly communicate platform and link to the precise artifact.
