### ISSUE TITLE
Support renaming a space

### ISSUE THREAD

**Issue by alfred-landrum** [brimsec/brim#675]

**Comment by philrz** [comment]
Now that https://github.com/brimsec/brim/issues/673 is addressed, it seems we could the remove the `.brim` extension from the Space name. Since the user is not really supposed to be seeing the directory anymore, it seems like redundant information. @alfred-landrum suggested we take care of that at the same time we're implementing these other issues related to Space name/rename.

**Comment by philrz** [comment]
The attached video shows the functionality working as of Brim commit `16a82e1`.

[Verify.mp4.zip](https://github.com/brimsec/brim/files/4703825/Verify.mp4.zip)
