### ISSUE TITLE
preferences window in dev mode triggers security warnings when choosing files

### ISSUE THREAD

**Issue by mikesbrown** [brimsec/brim#791]
If I'm running Brim in developer mode (e.g., `npm run electron`), when I pull up Preferences and attempt to select either a custom zeek runner or a JSON schema, an entry like this is logged to the console, and main.log:
```
09:36:26.672 › Security Warning: Prevented navigation to file:///Users/mikeb/git/brim/search.html?timeZone=UTC&timeFormat=&zeekRunner=&jsonTypeConfig=
```
dev tools console window looks like this:
```
  | consoleLog | @ | /Users/mikeb/git/bri…ports/console.js:91
  | transport | @ | /Users/mikeb/git/bri…ports/console.js:46
  | runTransport | @ | /Users/mikeb/git/bri…n-log/src/log.js:44
  | (anonymous) | @ | /Users/mikeb/git/bri…ransports/ipc.js:21
  | emit | @ | events.js:203
  | onMessage | @ | init.ts:50
```
This happens on my Mojave laptop and a Windows Server 2019 VM.

I also built a macOS release, installed it, and tested the same procedure. The security warnings don't appear there.

**Comment by mikesbrown** [comment]
At first I thought this prevented a schema from loading, but it seems like that's #792. In any case I filed this because this security warning doesn't print when you just try to ingest a pcap.

**Comment by jameskerr** [comment]
This issue has been resolved thanks to masons work in this PR: https://github.com/brimsec/brim/pull/816

I just tested this out on master and the warning is no longer there.

**Comment by jameskerr** [comment]
And for context, those security warnings were added by us here at brim. Since Electron allows you to navigate to a remote url, and gives that remote url full access to the user's file system via node, it's a security concern if the app ever "navigates" to a different page. We prevent navigation to any page except our own page (during reload for example), and log that warning. This was suggested in Electron's security best practices guide.

The button in the preferences was nested inside a <form> element. By default, browsers will submit the form whenever a <button> element within a form is clicked. The default "submit" behavior is to navigate the url specified in the <form action="/url-to-post-form-data">.

The fix mason put it prevents that default behavior, which is what we want.

**Comment by philrz** [comment]
Verified in Brim commit `c1dbca6`.

I first went back and reacquainted myself with the error in Brim commit `bc65b68` that came right before #816 was merged. Then with commit `c1dbca6` that's associated with the merge of #816, I can see the error no longer shows up in the Console, such as in this screenshot where I've clicked the button to select an altenate Zeek Runner.

![image](https://user-images.githubusercontent.com/5934157/83289307-b6f81000-a199-11ea-9b4a-5a616dabf772.png)

Thanks @mason-fish!
