### ISSUE TITLE
New Brim version notification for Linux

### ISSUE THREAD

**Issue by alfred-landrum** [brimsec/brim#855]
We don't currently support auto-update for Linux releases of Brim, as the Electron auto-updater mechanism ( https://www.electronjs.org/docs/api/auto-updater#platform-notices ) doesn't support it. We'll eventually shift to an auto-update mechanism that does support Linux; in the meantime, we should at least let Linux users know when there's a relevant update for them, and point them to the download page.

**Comment by mason-fish** [comment]
The behavior I'm planning to move forward with here is to make a request to our existing MacOS/Windows autoupdate server (would be this endpoint: https://update.electronjs.org/brimsec/brim/darwin-x64/0.5.3) to check if there is an update for MacOS/Windows, and if there **is** (i.e. the response returns a version number that is higher than the current one) then we can trigger a dialog which notifies the user of the new version and provides a link directly to the release tag on github. This will run every time on startup.

This will create a new constraint where every release will need to include all of our currently supported platforms, which is what we've already been doing. Otherwise if a MacOS-exclusive release comes out then our Linux users are going to get notified of a non-existent new version.

Longer term, I think we would like to move towards something like https://www.electron.build/ and https://www.electron.build/auto-update to handle our packaging and updating logic.

**Comment by alfred-landrum** [comment]
> The behavior I'm planning to move forward with here is to make a request to our existing MacOS/Windows autoupdate server (would be this endpoint: https://update.electronjs.org

@mason-fish and I discussed this earlier today: the rationale for this is that if Brim hits the GitHub api directly to check for releases, we'll eat into the api rate limits. The existing electronjs.org endpoint caches its results, so it doesn't consume rate limit credits as rapidly.

**Comment by philrz** [comment]
Verified in GA Brim tagged `v0.12.0`.

Since this logic went into GA Brim tagged `v0.11.0`, I started by running `v0.11.0`, opened the app, and immediately saw the notice of the new release. Here it was happening on Fedora:

![image](https://user-images.githubusercontent.com/5934157/85898182-ae065880-b7b0-11ea-83c6-9c61741fbabe.png)

Here it is on Ubuntu:

![image](https://user-images.githubusercontent.com/5934157/85898570-57e5e500-b7b1-11ea-8e24-32e3cb73e9a3.png)

Clicking the "Get Update" button brought me to https://github.com/brimsec/brim/releases/tag/v0.12.0.

Thanks @mason-fish!
