### ISSUE TITLE
mention our zeek as starting point for zeek customization

### ISSUE THREAD

**Issue by alfred-landrum** [brimsec/brim#958]
The zeek customization wiki should document that users can start with our pre-built zeek releases & try to add their zeek scripts onto a copy of it. See:

https://brimsec.slack.com/archives/C010DR0HHMF/p1596037523492400?thread_ts=1596031961.491000&cid=C010DR0HHMF

**Comment by philrz** [comment]
As I'd mentioned on the Slack thread, this seemed a little sticky to me, since `zeek-config` is not currently included with our Zeek artifacts, which would make it difficult to advocate the recommended approach of using [Zeek Package Manager](https://docs.zeek.org/projects/package-manager/en/stable/) to customize. Also, @nwt has confirmed that the plugin framework doesn’t work on Zeek-for-Windows yet, so for Windows (the most popular Brim platform) we'd also need to caveat that users would only be able to work with script-based packages.

All that said, since the downloadable binary artifacts _do_ provide a better starting point than compiling Zeek by hand (which would, indeed, be _very_ daunting for most to do on Windows), and _most_ Zeek packages seem to be script-based, I agree it would be reasonable for us to walk through an example on the wiki that starts with a Brim Zeek artifact and unpacks the scripts from a Zeek package into the correct location.

**Comment by philrz** [comment]
The wiki write-up for this is at:

https://github.com/brimsec/brim/wiki/Zeek-Customization#creating-your-customized-zeek
